basePath: /api/v1
definitions:
  model.AccountInfo:
    properties:
      avatars:
        type: string
      id:
        example: 1
        type: integer
      username:
        example: Anxiu
        type: string
    type: object
  model.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
      msg:
        type: string
    type: object
  model.TokenData:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user: {}
    type: object
  service.UserService:
    properties:
      age:
        example: 20
        type: integer
      email:
        example: email@example.com
        type: string
      gender:
        example: 1
        type: integer
      tel:
        example: 188-8888-6666
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: anxiu.fyc@foxmail.com
    name: Anxiu0101
    url: https://github.com/Anxiu0101/MedicalCare/blob/master/README.md
  description: This is MedicalCare Project api docs.
  title: MedicalCare API
  version: "1.0"
paths:
  /api/v1/blog:
    post:
      consumes:
      - application/json
      description: 用于新建文章
      parameters:
      - description: Authorization
        in: header
        name: x-token
        required: true
        type: string
      - description: 文章标题
        in: formData
        name: title
        required: true
        type: string
      - description: 文章简介
        in: formData
        name: desc
        type: string
      - description: 文章内容
        in: formData
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - x-token: []
      summary: 文章发布接口
      tags:
      - 文章相关接口
  /api/v1/user/info:
    get:
      consumes:
      - application/json
      description: 用于用户获取其个人资料
      parameters:
      - description: Authorization
        in: header
        name: x-token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  $ref: '#/definitions/service.UserService'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - x-token: []
      summary: 用户资料获取接口
      tags:
      - 用户相关接口
    put:
      consumes:
      - application/json
      description: 用于用户更新其个人资料
      parameters:
      - description: Authorization
        in: header
        name: x-token
        required: true
        type: string
      - description: 用户邮箱
        in: formData
        name: email
        type: string
      - description: 用户性别
        in: formData
        name: gender
        type: integer
      - description: 用户年龄
        in: formData
        name: age
        type: integer
      - description: 联系方式
        in: formData
        name: tel
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - x-token: []
      summary: 用户资料更新接口
      tags:
      - 用户相关接口
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: 用于用户登陆，接受用户名和用户密码，将 access token 和 refresh token 作为结果返回，同时返回用户的账户信息
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/model.TokenData'
                  - properties:
                      User:
                        $ref: '#/definitions/model.AccountInfo'
                    type: object
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户登陆接口
      tags:
      - 用户相关接口
  /api/v1/user/password:
    post:
      consumes:
      - application/json
      description: 用于用户更新密码，需要新密码做为传入的参数，需要 token 验证
      parameters:
      - description: Authorization
        in: header
        name: x-token
        required: true
        type: string
      - description: 新密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - x-token: []
      summary: 用户重新设置密码接口
      tags:
      - 用户相关接口
  /api/v1/user/register:
    post:
      consumes:
      - application/json
      description: 用于注册新用户，传入 username 和 password 作为新用户的 username 和 password
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 用户密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      summary: 用户注册接口
      tags:
      - 用户相关接口
  /chat/:receiver:
    get:
      consumes:
      - application/json
      description: 用于聊天室的使用
      parameters:
      - description: Authorization
        in: header
        name: x-token
        required: true
        type: string
      - description: 聊天对象
        in: path
        name: receiver
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.Response'
      security:
      - x-token: []
      summary: 聊天室接口
      tags:
      - 聊天室相关接口
  /group:
    post:
      consumes:
      - application/json
      description: set up a group
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: create group
      tags:
      - user
  /group/member:
    put:
      consumes:
      - application/json
      description: invite group members
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: invite member
      tags:
      - user
swagger: "2.0"
